/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(apps)'}/bookatable` | `/bookatable`; params?: Router.UnknownInputParams; } | { pathname: `${'/(apps)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(apps)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(apps)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(apps)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(splash)'}/splash` | `/splash`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(apps)'}/bookatable` | `/bookatable`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(apps)'}/categories` | `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(apps)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(apps)'}/orders` | `/orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(apps)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(splash)'}/splash` | `/splash`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(apps)'}/bookatable${`?${string}` | `#${string}` | ''}` | `/bookatable${`?${string}` | `#${string}` | ''}` | `${'/(apps)'}/categories${`?${string}` | `#${string}` | ''}` | `/categories${`?${string}` | `#${string}` | ''}` | `${'/(apps)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(apps)'}/orders${`?${string}` | `#${string}` | ''}` | `/orders${`?${string}` | `#${string}` | ''}` | `${'/(apps)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/otp${`?${string}` | `#${string}` | ''}` | `/otp${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(splash)'}/splash${`?${string}` | `#${string}` | ''}` | `/splash${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(apps)'}/bookatable` | `/bookatable`; params?: Router.UnknownInputParams; } | { pathname: `${'/(apps)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(apps)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(apps)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(apps)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(splash)'}/splash` | `/splash`; params?: Router.UnknownInputParams; };
    }
  }
}
